name: Deploy
on:
   push:
      branches:
         - prod
jobs:
   build:
      name: Build
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repo
           uses: actions/checkout@master
         - name: Install Dependencies
           run: npm ci
         - name: Build Server
           run: npm run build:prod:server
         - name: Build Client
           run: npm run build:prod:client
         - name: Archive Production Artifact
           uses: actions/upload-artifact@master
           with:
              name: dist
              path: dist
   deploy-front-end:
      name: Deploy Front-End
      needs: [build]
      runs-on: ubuntu-latest
      steps:
         - name: Download Artifact
           uses: actions/download-artifact@master
           with:
              name: dist
              path: dist
         - name: Deploy 🚀
           uses: JamesIves/github-pages-deploy-action@3.7.1
           with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages
              FOLDER: dist/client
   deploy-back-end:
      name: Deploy Back-End
      needs: [build]
      runs-on: ubuntu-latest
      steps:
         - name: Clone Glitch Project
           run: git clone https://${{ secrets.GLITCH_GIT_TOKEN }}@api.glitch.com/git/game-off
         - name: Clear Repo
           run: |
              cd game-off
              rm -v !(".git")
         - name: Download Artifact
           uses: actions/download-artifact@master
           with:
              name: dist
              path: game-off
         - name: Deploy 🚀
           run: |
              cd game-off
              git commit -m "Deploying Server"
              git push
