name: Deploy
on:
   push:
      branches:
         - prod
jobs:
   build-front-end:
      name: Build Front End
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repo
           uses: actions/checkout@master
         - name: Install Dependencies
           run: npm ci
         - name: Build Client
           run: npm run build:prod:client
         - name: Archive Production Artifact
           uses: actions/upload-artifact@master
           with:
              name: dist-client
              path: dist/client
   build-back-end:
      name: Build Back End
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repo
           uses: actions/checkout@master
         - name: Install Dependencies
           run: npm ci
         - name: Build Server
           run: npm run build:prod:server
         - name: Archive Production Artifact
           uses: actions/upload-artifact@master
           with:
              name: dist-server
              path: dist/server
   deploy-front-end:
      name: Deploy Front-End
      needs: [build-front-end, build-back-end]
      runs-on: ubuntu-latest
      steps:
         - name: Download Artifact
           uses: actions/download-artifact@master
           with:
              name: dist-client
              path: dist
         - name: Deploy 🚀
           uses: JamesIves/github-pages-deploy-action@3.7.1
           with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages
              FOLDER: dist
   deploy-back-end:
      name: Deploy Back-End
      needs: [build-front-end, build-back-end]
      runs-on: ubuntu-latest
      steps:
         - name: Clone Glitch Project
           run: git clone https://${{ secrets.GLITCH_GIT_TOKEN }}@api.glitch.com/git/game-off
         - name: Clear Repo
           run: find ./game-off -mindepth 1 ! -regex '^./game-off/\.git\(/.*\)?' -delete
         - name: Download Artifact
           uses: actions/download-artifact@master
           with:
              name: dist-server
              path: game-off
         - name: Deploy 🚀
           run: |
              cd game-off
              git config --global user.email "actions@github.com"
              git config --global user.name "GitHub Actions"
              git add .
              git commit -m "Deploying Server"
              git push
